version: '3'

services:

  tevuna-visual:
    build: 
      context: ./visual_api
      dockerfile: Dockerfile
    container_name: "tevuna-visual-api"
    ports:
      - "5000:80"
    restart: unless-stopped

  tevuna-analysis:
    build:
      context: ./bias_api
      dockerfile: Dockerfile
    container_name: "tevuna-bias-api"
    ports:
      - "5010:80"
    restart: unless-stopped